version: '3'

services:
  web:
    container_name: web
    build: ./App
    volumes:
      - ./html:/var/www/html
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./MySQL
    volumes:
      - ./MySQL/DB:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kstm
    ports:
      - "3306:3306"
    command: bash -c 'usermod -o -u $LINUX_MYSQL_UID mysql; groupmod -o -g $LINUX_MYSQL_GID mysql; chown -R mysql:root /var/run/mysqld/ /var/log/mysql/ /var/lib/mysql/; /entrypoint.sh mysqld --user=mysql --console'
