version: '3'

services:
  web:
    container_name: web
    build: ./App
    volumes:
      - ./html:/var/www/html
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./MySQL
    volumes:
      - ./MySQL/DB:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kstm
    ports:
      - "3306:3306"
